version: '3.7'

x-base: &base
  networks: 
    - events

services:

  proxy:
    image: nginx:latest
    container_name: events.proxy
    <<: *base
    ports: 
      - "80:80"
    volumes: 
      - ./proxy/:/etc/nginx/:ro
    depends_on: 
      - backend
      - frontend

  frontend:
    image: events.frontend
    container_name: events.frontend
    <<: *base
    build: 
      context: ./frontend/
      dockerfile: DockerFile
    ports: 
      - "8081:8081"

  db:
    image: microsoft/mssql-server-linux:latest
    container_name: events.db
    <<: *base
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Very123Str!
    expose:
      - 1433
      
  backend:
      image: events.app
      container_name: events.app
      <<: *base
      build:
        context: ./backend/Sample.DockerApplication/
        dockerfile: ./backend/Dockerfile
      environment:
        - ConnectionStrings__DefaultConnection=Server=db;Initial Catalog=events;User ID=sa;Password=Very123Str!;
      ports:
        - "8082:8082"
      depends_on: 
        - frontend
    
networks: 
  events:
    driver: bridge