version: '3'

services:
  proxy:
    image: events.proxy
    container_name: events.proxy
    build: 
      context: ./proxy/
      dockerfile: DockerFile
    links:
      - backend
      - frontend
    ports: 
      - "80:80"
  frontend:
    image: events.frontend
    container_name: events.frontend
    build: 
      context: ./frontend/
      dockerfile: DockerFile
    ports: 
      - "8081:8081"
    depends_on:
      - backend
  db:
    image: microsoft/mssql-server-linux:latest
    container_name: events.db
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Very123Str!
    expose:
      - 1433
  backend:
      image: events.app
      container_name: events.app
      build:
        context: ./backend/Sample.DockerApplication
        dockerfile: ./Sample.DockerApplication.Web/Dockerfile
      environment:
        - ConnectionStrings__DefaultConnection=Server=db;Initial Catalog=events;User ID=sa;Password=Very123Str!;
      ports:
        - "8082:8082"
      links:
        - db:db
      depends_on:
        - db
    