// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.DockerApplication.Dal;

namespace Sample.DockerApplication.Dal.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20190218180523_InitialData")]
    partial class InitialData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long?>("EventProgramId");

                    b.Property<string>("ImageLink");

                    b.Property<bool>("IsRegistrationOpen");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("EventProgramId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
                            EventProgramId = 1L,
                            IsRegistrationOpen = false,
                            StartDate = new DateTime(2019, 2, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Technology Conference"
                        });
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.EventProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("EventPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1L
                        });
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Presentation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Company");

                    b.Property<TimeSpan>("EndTime");

                    b.Property<long?>("EventProgramId");

                    b.Property<TimeSpan>("StartTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("EventProgramId");

                    b.ToTable("Presentations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Author = "John Smith",
                            Company = "VeryCoolCompany Inc.",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            EventProgramId = 1L,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "A quick guide to help you understand and create ReactJS apps"
                        },
                        new
                        {
                            Id = 2L,
                            Author = "Robert Johnson",
                            Company = "BigCompany Inc.",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            EventProgramId = 1L,
                            StartTime = new TimeSpan(0, 12, 0, 0, 0),
                            Title = "ASP.NET Web Deployment using Visual Studio"
                        },
                        new
                        {
                            Id = 3L,
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            EventProgramId = 1L,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Title = "Coffee"
                        },
                        new
                        {
                            Id = 4L,
                            Author = "David Linthicum",
                            Company = "Deloitte Consulting",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            EventProgramId = 1L,
                            StartTime = new TimeSpan(0, 15, 0, 0, 0),
                            Title = "Here are 9 effective best practices for using DevOps in the cloud"
                        });
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Event", b =>
                {
                    b.HasOne("Sample.DockerApplication.Dal.Entities.EventProgram", "EventProgram")
                        .WithMany()
                        .HasForeignKey("EventProgramId");
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Presentation", b =>
                {
                    b.HasOne("Sample.DockerApplication.Dal.Entities.EventProgram")
                        .WithMany("Presentations")
                        .HasForeignKey("EventProgramId");
                });
#pragma warning restore 612, 618
        }
    }
}
