// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.DockerApplication.Dal;

namespace Sample.DockerApplication.Dal.Migrations
{
    [DbContext(typeof(SampleContext))]
    partial class SampleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long?>("EventProgramId");

                    b.Property<string>("ImageLink");

                    b.Property<bool>("IsRegistrationOpen");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("EventProgramId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.EventProgram", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("EventPrograms");
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Presentation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author");

                    b.Property<string>("Company");

                    b.Property<DateTime>("EndTime");

                    b.Property<long?>("EventProgramId");

                    b.Property<DateTime>("StartTime");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("EventProgramId");

                    b.ToTable("Presentations");
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Event", b =>
                {
                    b.HasOne("Sample.DockerApplication.Dal.Entities.EventProgram", "EventProgram")
                        .WithMany()
                        .HasForeignKey("EventProgramId");
                });

            modelBuilder.Entity("Sample.DockerApplication.Dal.Entities.Presentation", b =>
                {
                    b.HasOne("Sample.DockerApplication.Dal.Entities.EventProgram")
                        .WithMany("Presentations")
                        .HasForeignKey("EventProgramId");
                });
#pragma warning restore 612, 618
        }
    }
}
